/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as SUuidRouteImport } from './app/s/$uuid'
import { Route as SUuidIndexRouteImport } from './app/s/$uuid/index'
import { Route as SUuidVersionIdRouteImport } from './app/s/$uuid/$versionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SUuidRoute = SUuidRouteImport.update({
  id: '/s/$uuid',
  path: '/s/$uuid',
  getParentRoute: () => rootRouteImport,
} as any)
const SUuidIndexRoute = SUuidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SUuidRoute,
} as any)
const SUuidVersionIdRoute = SUuidVersionIdRouteImport.update({
  id: '/$versionId',
  path: '/$versionId',
  getParentRoute: () => SUuidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s/$uuid': typeof SUuidRouteWithChildren
  '/s/$uuid/$versionId': typeof SUuidVersionIdRoute
  '/s/$uuid/': typeof SUuidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s/$uuid/$versionId': typeof SUuidVersionIdRoute
  '/s/$uuid': typeof SUuidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s/$uuid': typeof SUuidRouteWithChildren
  '/s/$uuid/$versionId': typeof SUuidVersionIdRoute
  '/s/$uuid/': typeof SUuidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s/$uuid' | '/s/$uuid/$versionId' | '/s/$uuid/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s/$uuid/$versionId' | '/s/$uuid'
  id: '__root__' | '/' | '/s/$uuid' | '/s/$uuid/$versionId' | '/s/$uuid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SUuidRoute: typeof SUuidRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$uuid': {
      id: '/s/$uuid'
      path: '/s/$uuid'
      fullPath: '/s/$uuid'
      preLoaderRoute: typeof SUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$uuid/': {
      id: '/s/$uuid/'
      path: '/'
      fullPath: '/s/$uuid/'
      preLoaderRoute: typeof SUuidIndexRouteImport
      parentRoute: typeof SUuidRoute
    }
    '/s/$uuid/$versionId': {
      id: '/s/$uuid/$versionId'
      path: '/$versionId'
      fullPath: '/s/$uuid/$versionId'
      preLoaderRoute: typeof SUuidVersionIdRouteImport
      parentRoute: typeof SUuidRoute
    }
  }
}

interface SUuidRouteChildren {
  SUuidVersionIdRoute: typeof SUuidVersionIdRoute
  SUuidIndexRoute: typeof SUuidIndexRoute
}

const SUuidRouteChildren: SUuidRouteChildren = {
  SUuidVersionIdRoute: SUuidVersionIdRoute,
  SUuidIndexRoute: SUuidIndexRoute,
}

const SUuidRouteWithChildren = SUuidRoute._addFileChildren(SUuidRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SUuidRoute: SUuidRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
